// Auto-generated from real Semrush keyword data (Keyword Export/_processed/FINAL_clean_ascii.csv),
// matched against the actual live product/category names. Volume and Keyword Difficulty (KD)
// are real Semrush metrics. Weak single-token matches were gated to a verified category keyword
// rather than shipped as a misleading primary (see weakPrimaryGated).

export interface ProductKeywordEntry {
  primaryKeyword: string;
  primaryVolume: number;
  primaryKd: number;
  primaryIntent: string;
  supporting: string[];
  weakPrimaryGated: boolean;
}

export const PRODUCT_KEYWORDS: Record<string, ProductKeywordEntry> = {
  "Dry-Aged O'Connor Ribeye Steak Bone-In": {
    primaryKeyword: "dry aged ribeye on the bone",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["dry aged t bone steak", "ribeye steak dry aged", "dry aged bone in ribeye", "ribeye dry aged steak", "dry aged t-bone steak"],
    weakPrimaryGated: false,
  },
  "Southern Gold Angus Scotch Fillet Steaks": {
    primaryKeyword: "scotch fillet steaks",
    primaryVolume: 140,
    primaryKd: 9.0,
    primaryIntent: "Informational",
    supporting: ["pork scotch fillet steaks", "best way to cook scotch fillet steaks", "how to cut scotch fillet into steaks", "steaks scotch fillet", "best way to cook pork scotch fillet steaks"],
    weakPrimaryGated: false,
  },
  "Centre-Cut Grass-Fed Eye Fillet Steaks": {
    primaryKeyword: "grass fed eye fillet",
    primaryVolume: 110,
    primaryKd: 7.0,
    primaryIntent: "Commercial",
    supporting: ["grass fed beef eye fillet", "coles grass fed eye fillet", "eye fillet steaks", "grass fed scotch fillet", "grass-fed beef steaks"],
    weakPrimaryGated: false,
  },
  "Dry-Aged Bistecca alla Fiorentina T-Bone": {
    primaryKeyword: "dry aged rib eye on the bone",
    primaryVolume: 30,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["dry aged t bone", "dry aged bone in striploin", "dry aged bone in sirloin", "dry aged bone in ribeye", "dry aged bistecca"],
    weakPrimaryGated: false,
  },
  "Full Packer Competition Angus Brisket Point End": {
    primaryKeyword: "wagyu point end brisket",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["bulk angus brisket options", "brisket angus beef", "wagyu brisket point", "angus brisket price", "how much is a full brisket"],
    weakPrimaryGated: false,
  },
  "Asado Cross-Cut Flanken Beef Short Ribs": {
    primaryKeyword: "beef short ribs cross cut",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["cross cut beef short ribs", "beef ribs flanken style", "beef flanken ribs near me", "beef ribs flanken", "flanken cut short ribs"],
    weakPrimaryGated: false,
  },
  "100% Trimmed Grass-Fed Beef Cheeks": {
    primaryKeyword: "grass fed ground beef",
    primaryVolume: 140,
    primaryKd: 5.0,
    primaryIntent: "Informational, Commercial",
    supporting: ["grass fed beef mince", "grass fed beef", "grass fed beef australia", "grass fed beef sausages", "grass fed beef brisket"],
    weakPrimaryGated: false,
  },
  "Premium Grass-Fed Beef Mince (1kg Family Pack)": {
    primaryKeyword: "grass fed beef mince",
    primaryVolume: 260,
    primaryKd: 6.0,
    primaryIntent: "Commercial",
    supporting: ["grass fed beef mince aldi", "grass fed mince beef", "woolworths grass fed beef mince nutrition", "grass fed beef mince calories", "grass fed beef mince nutrition"],
    weakPrimaryGated: false,
  },
  "Mega Bulk Beef Mince (2kg Value Pack)": {
    primaryKeyword: "extra lean beef mince",
    primaryVolume: 2400,
    primaryKd: 11.0,
    primaryIntent: "Commercial",
    supporting: ["beef mince", "lean beef mince", "bulk beef mince", "buy organic beef mince online", "beef mince melbourne"],
    weakPrimaryGated: false,
  },
  "Angus Beef Burger Patties (6 x 150g)": {
    primaryKeyword: "wagyu beef burger patties",
    primaryVolume: 110,
    primaryKd: 8.0,
    primaryIntent: "Commercial",
    supporting: ["ground beef burger patties", "gippsland pure angus beef burger", "ground beef into burger patties", "burger patties from ground beef", "best homemade beef burger patties"],
    weakPrimaryGated: false,
  },
  "Tender Diced Casserole Beef Chuck": {
    primaryKeyword: "coles beef chuck casserole steak",
    primaryVolume: 30,
    primaryKd: 19.0,
    primaryIntent: "Navigational",
    supporting: ["how to cook diced beef so it's tender", "how to cook diced beef tender", "how to cook diced beef to make it tender", "how long to boil diced beef to make it tender", "what is diced casserole beef"],
    weakPrimaryGated: false,
  },
  "Marinated Garlic & Rosemary Eye Fillet Skewers": {
    primaryKeyword: "marinated eye fillet recipes",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["marinated eye fillet", "eye fillet steak", "eye fillet", "roast eye fillet", "beef eye fillet"],
    weakPrimaryGated: false,
  },
  "Long-Bone Tomahawk Steak MBS 5+": {
    primaryKeyword: "t bone steak price",
    primaryVolume: 110,
    primaryKd: 3.0,
    primaryIntent: "Transactional",
    supporting: ["beef blade steak bone in", "beef t bone steak", "ribeye steak bone in", "rib eye bone in steak recipe", "beef rib eye steak bone in recipe"],
    weakPrimaryGated: false,
  },
  "Whole Strip Loin Primal Cryovac (4kg)": {
    primaryKeyword: "wagyu strip loin steaks",
    primaryVolume: 140,
    primaryKd: 5.0,
    primaryIntent: "Commercial",
    supporting: ["strip loin new york steak", "new york strip loin steak", "whole new york strip loin", "new york strip whole loin", "boneless new york strip loin"],
    weakPrimaryGated: false,
  },
  "Whole Scotch Fillet Cube Roll Primal (3.8kg)": {
    primaryKeyword: "cube roll scotch fillet",
    primaryVolume: 30,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["cube roll vs scotch fillet", "is cube roll scotch fillet", "roll of scotch fillet", "how to cook a scotch fillet roll", "scotch fillet"],
    weakPrimaryGated: false,
  },
  "Traditional English Cut Dino Beef Ribs (3-Bone)": {
    primaryKeyword: "bone in beef short ribs near me",
    primaryVolume: 10,
    primaryKd: 19.0,
    primaryIntent: "Transactional",
    supporting: ["beef short ribs bone in near me", "where to buy bone in beef short ribs", "short ribs with bone", "grill short ribs bone in", "bone short ribs"],
    weakPrimaryGated: false,
  },
  "Thick-Cut Rump Steaks (4 x 250g)": {
    primaryKeyword: "rump cap steaks",
    primaryVolume: 50,
    primaryKd: 7.0,
    primaryIntent: "Informational",
    supporting: ["rump steaks", "rump steaks recipes", "best way to cook rump steaks", "difference between rump and sirloin steaks", "wholesale ribeye steaks"],
    weakPrimaryGated: false,
  },
  "Flat Iron Oyster Blade Steaks (3 x 200g)": {
    primaryKeyword: "flat iron oyster blade",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["flat iron steak vs oyster blade", "flat iron vs oyster blade", "oyster blade flat iron", "oyster blade vs flat iron", "are oyster blade steaks good"],
    weakPrimaryGated: false,
  },
  "Skirt Steak (Arrachera Cut) for Tacos": {
    primaryKeyword: "skirt steak coles",
    primaryVolume: 210,
    primaryKd: 28.0,
    primaryIntent: "Informational, Transactional",
    supporting: ["skirt steak coles price", "skirt steak australia coles", "skirt steak price australia", "black opal skirt steak", "is sizzle steak the same as skirt steak"],
    weakPrimaryGated: false,
  },
  "Picanha Rump Cap Whole with Fat Cap": {
    primaryKeyword: "wagyu rump cap",
    primaryVolume: 480,
    primaryKd: 7.0,
    primaryIntent: "Informational",
    supporting: ["rump cap steaks", "rump cap wagyu", "rump cap steak australia", "rump cap steak near me", "rump cap steak price"],
    weakPrimaryGated: false,
  },
  "Osso Buco Beef Shank Cross-Cut Rings": {
    primaryKeyword: "beef mince",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["wagyu cross beef", "beef short ribs cross cut", "cross cut beef short ribs", "cross cut beef marrow bones", "pork and beef cross contamination"],
    weakPrimaryGated: true,
  },
  "Tri-Tip California Santa Maria Roast": {
    primaryKeyword: "dry aged tri tip",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["japanese a5 wagyu tri tip", "roast eye fillet", "beef eye fillet roast", "eye fillet roast", "eye fillet roast cooking time"],
    weakPrimaryGated: false,
  },
  "Boneless Rolled Beef Ribeye Roast": {
    primaryKeyword: "boneless beef shoulder roast",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["beef boneless blade roast recipe", "beef boneless blade roast", "boneless beef blade roast cooking time", "boneless beef blade roast recipe", "boneless beef blade roast slow cooker"],
    weakPrimaryGated: false,
  },
  "Slow-Cook Beef Shin Gravy Meat": {
    primaryKeyword: "gravy beef slow cook",
    primaryVolume: 140,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["slow cook beef and gravy", "slow cook beef in gravy", "slow cook gravy beef recipes", "slow cook gravy beef casserole", "slow cook gravy beef recipe"],
    weakPrimaryGated: false,
  },
  "Minute Steaks Thin-Sliced for Sandwiches": {
    primaryKeyword: "wholesale ribeye steaks",
    primaryVolume: 90,
    primaryKd: 2.0,
    primaryIntent: "Informational",
    supporting: ["eye fillet steaks", "sliced wagyu", "chicken steaks", "wagyu strip loin steaks", "scotch fillet steaks"],
    weakPrimaryGated: false,
  },
  "Thick Cut Porterhouse / Sirloin (2 x 300g)": {
    primaryKeyword: "black angus porterhouse",
    primaryVolume: 110,
    primaryKd: 2.0,
    primaryIntent: "Informational",
    supporting: ["wagyu sirloin", "wagyu beef sirloin", "wagyu beef sirloin steak", "porterhouse steak price per kg", "angus porterhouse"],
    weakPrimaryGated: false,
  },
  "Corned Silverside Beef Roast with Spices": {
    primaryKeyword: "beef eye fillet roast",
    primaryVolume: 720,
    primaryKd: 6.0,
    primaryIntent: "Informational",
    supporting: ["roast eye fillet beef recipe", "beef bolar blade roast", "beef eye fillet roast recipe", "roast beef eye fillet cooking time", "eye fillet beef roast"],
    weakPrimaryGated: false,
  },
  "Beef Short Rib Chuck Strips (Boneless)": {
    primaryKeyword: "boneless beef rib eye",
    primaryVolume: 210,
    primaryKd: 46.0,
    primaryIntent: "Informational",
    supporting: ["rib of beef boneless", "rib eye boneless steak", "short rib boneless", "boneless short rib meat", "short rib vs chuck"],
    weakPrimaryGated: false,
  },
  "Marrow Bones Canoe-Cut for Roasting": {
    primaryKeyword: "beef marrow bones canoe cut",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["roasting beef marrow bones for stock", "roasting beef marrow bones", "canoe cut beef marrow bones", "beef bone marrow bones", "beef marrow bones for bone broth"],
    weakPrimaryGated: false,
  },
  "Smoked Pulled Beef Point End (Pre-Cooked)": {
    primaryKeyword: "pre cooked beef patties",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["pre cooked sausages australia", "pre cooked mince", "pre cooked meat delivery", "pre cooked meat suppliers", "pre cooked meat near me"],
    weakPrimaryGated: false,
  },
  "Beef Sirloin Roast Basting Cut": {
    primaryKeyword: "dry aged sirloin roast",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["beef eye fillet roast", "roast eye fillet beef recipe", "beef bolar blade roast", "wagyu beef sirloin", "beef eye fillet roast recipe"],
    weakPrimaryGated: false,
  },
  "Smash Burger Ground Chuck & Brisket Blend (80/20)": {
    primaryKeyword: "burger patty ground beef",
    primaryVolume: 50,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["ground beef burger patties", "burger patty from ground beef", "wagyu smash burger", "higher ground wagyu brisket", "wagyu brisket higher ground"],
    weakPrimaryGated: false,
  },
  "Beef Topside Sliced for Jerky / Biltong": {
    primaryKeyword: "topside beef",
    primaryVolume: 1300,
    primaryKd: 12.0,
    primaryIntent: "Informational",
    supporting: ["topside beef mince", "sliced beef coles", "beef topside recipes", "topside wagyu beef", "1.5 kg beef topside cooking time"],
    weakPrimaryGated: false,
  },
  "Beef Tail (Oxtail) Discs for Soups": {
    primaryKeyword: "beef mince",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["beef eye fillet tail", "beef eye fillet tail recipe", "beef fillet tail", "beef tail fillet", "beef fillet tail recipes"],
    weakPrimaryGated: true,
  },
  "Beef Skirt Fajita Slices Marinated in Lime & Cumin": {
    primaryKeyword: "wagyu beef slices",
    primaryVolume: 110,
    primaryKd: 2.0,
    primaryIntent: "Informational, Transactional",
    supporting: ["marinated beef fillet", "skirt beef australia", "beef skirt coles", "marinated diced beef", "beef steak slices recipes"],
    weakPrimaryGated: false,
  },
  "T-Bone Classic Backyard Steaks (2 x 400g)": {
    primaryKeyword: "t bone steaks",
    primaryVolume: 40,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["how many t bone steaks in half a cow", "bison bone-in cowboy 18 oz. ribeye steaks total 144 oz", "bone beef", "beef bone marrow bones", "wholesale ribeye steaks"],
    weakPrimaryGated: false,
  },
  "Grass-Fed Beef Eye of Rump Rostbif": {
    primaryKeyword: "grass fed beef eye fillet",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["grass fed beef rump", "grass fed beef eye", "grass fed rump", "grass fed eye fillet", "grass fed rump steak"],
    weakPrimaryGated: false,
  },
  "Beef Short Rib Single Bone Dinosaur Cut (800g)": {
    primaryKeyword: "beef rib eye steak bone in recipe",
    primaryVolume: 30,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["rib of beef bone in", "beef rib eye bone in", "single beef rib", "beef rib eye on the bone", "rib eye with bone"],
    weakPrimaryGated: false,
  },
  "Beef Chuck Roll Primal for DIY Pitmasters (5kg)": {
    primaryKeyword: "chuck eye roll beef",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["wagyu beef chuck roll", "wagyu beef chuck eye roll", "beef chuck eye roll recipe", "what is beef chuck eye roll", "black angus chuck eye roll"],
    weakPrimaryGated: false,
  },
  "Wagyu Cube Roll (Scotch Fillet) MBS 9+": {
    primaryKeyword: "cube roll scotch fillet",
    primaryVolume: 30,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["cube roll vs scotch fillet", "is cube roll scotch fillet", "roll of scotch fillet", "how to cook a scotch fillet roll", "wagyu scotch fillet"],
    weakPrimaryGated: false,
  },
  "Wagyu Long-Bone Tomahawk MBS 8-9": {
    primaryKeyword: "wagyu beef",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["bone marrow wagyu", "t bone wagyu", "wagyu a5 tomahawk", "a5 wagyu tomahawk steak", "a5 wagyu tomahawk price"],
    weakPrimaryGated: true,
  },
  "Wagyu Whole Rump Cap (Picanha) MBS 7+": {
    primaryKeyword: "wagyu rump cap",
    primaryVolume: 480,
    primaryKd: 7.0,
    primaryIntent: "Informational",
    supporting: ["rump cap wagyu", "how to cook wagyu rump cap", "roast wagyu rump cap", "wagyu rump cap roast", "wagyu rump cap steak"],
    weakPrimaryGated: false,
  },
  "Japanese A5 Black Wagyu Striploin Cut": {
    primaryKeyword: "japanese black wagyu beef",
    primaryVolume: 70,
    primaryKd: 18.0,
    primaryIntent: "Informational",
    supporting: ["japanese black wagyu", "japanese black wagyu steak", "japanese black wagyu cow", "japanese black beef vs wagyu", "japanese black wagyu cattle"],
    weakPrimaryGated: false,
  },
  "Wagyu Brisket Point End Marbled MBS 8+": {
    primaryKeyword: "wagyu point end brisket",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["wagyu brisket point", "buy brisket point", "brisket point for sale", "what is point cut brisket", "what is brisket point cut"],
    weakPrimaryGated: false,
  },
  "Wagyu Shabu Shabu & Sukiyaki Wafer Slices": {
    primaryKeyword: "wagyu beef slices",
    primaryVolume: 110,
    primaryKd: 2.0,
    primaryIntent: "Informational, Transactional",
    supporting: ["a5 wagyu slices", "how to cook thin wagyu slices", "how to cook wagyu beef slices", "how to cook wagyu beef thin slices", "how to cook wagyu slices"],
    weakPrimaryGated: false,
  },
  "Wagyu Eye Fillet Medallions MBS 7+ (2 x 200g)": {
    primaryKeyword: "eye fillet medallions",
    primaryVolume: 30,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["wagyu eye fillet", "eye fillet wagyu", "wagyu beef eye fillet", "wagyu eye fillet price", "how to cook wagyu eye fillet"],
    weakPrimaryGated: false,
  },
  "Wagyu Smash Burger Gourmet Patties (4 x 180g)": {
    primaryKeyword: "wagyu beef burger patties",
    primaryVolume: 110,
    primaryKd: 8.0,
    primaryIntent: "Commercial",
    supporting: ["wagyu smash burger", "smash wagyu burger", "wagyu burger patties near me", "wagyu burger patties recipe", "how to cook wagyu burger patties"],
    weakPrimaryGated: false,
  },
  "Wagyu Short Rib Flanken Cut Kalbi MBS 8+": {
    primaryKeyword: "short rib flanken cut",
    primaryVolume: 30,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["flanken cut short rib", "flanken style short rib", "wagyu rib fillet", "wagyu short rib", "wagyu rib eye"],
    weakPrimaryGated: false,
  },
  "Wagyu Beef Bresaola Dry-Cured Slices (200g)": {
    primaryKeyword: "dry cured bacon australia",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["does dry cured bacon contain nitrates", "wagyu beef slices", "dry aged wagyu beef", "how to cook wagyu beef slices", "how to cook wagyu beef thin slices"],
    weakPrimaryGated: false,
  },
  "The Executive Pitmaster Smoker Feast Box (14kg)": {
    primaryKeyword: "meat smoker subscription box",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Transactional",
    supporting: ["beef box", "bbq in a box", "meat box", "what is meat box", "chicken box"],
    weakPrimaryGated: false,
  },
  "The Essential Family Bulk Meat Box (18kg)": {
    primaryKeyword: "meat box",
    primaryVolume: 2400,
    primaryKd: 23.0,
    primaryIntent: "Commercial",
    supporting: ["what is meat box", "box for meat", "meat box wa", "meat box perth", "meat subscription box"],
    weakPrimaryGated: false,
  },
  "Gym High-Protein 10-Pack Lean Rump Box (2.5kg)": {
    primaryKeyword: "chicken breast high protein",
    primaryVolume: 480,
    primaryKd: 34.0,
    primaryIntent: "Informational",
    supporting: ["lean mince beef protein", "lean beef mince protein", "high protein chicken breast", "lean rump steak", "protein in lean beef mince"],
    weakPrimaryGated: false,
  },
  "Weekly Protein Meal Prep Master Box (12kg)": {
    primaryKeyword: "high protein beef mince meal prep",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["beef mince meal prep high protein", "chicken breast protein meal prep", "beef mince meal prep ideas", "low calorie mince meal prep", "weekly meat box"],
    weakPrimaryGated: false,
  },
  "The Great Australian BBQ Party Box (10kg)": {
    primaryKeyword: "bbq in a box",
    primaryVolume: 110,
    primaryKd: 0.0,
    primaryIntent: "Commercial",
    supporting: ["big box bbq canberra", "big box bbq narrabundah", "bbq meat box", "meat box bbq", "australian meat box"],
    weakPrimaryGated: false,
  },
  "Dry-Aged Steak Connoisseur Tasting Box (4kg)": {
    primaryKeyword: "porterhouse steak dry aged",
    primaryVolume: 40,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["dry aged porterhouse steak", "dry aged steak brisbane", "dry aged steak sydney", "dry aged rump steak", "dry aged steak restaurant"],
    weakPrimaryGated: false,
  },
  "All-Day Carnivore Zero-Carb Pack (15kg)": {
    primaryKeyword: "carnivore 1 meal a day",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["carnivore day", "carnivore how much meat per day", "how much meat per day on carnivore", "carnivore meats", "carnivore prep meals"],
    weakPrimaryGated: false,
  },
  "Winter Slow-Cook & Braise Feast Box (9kg)": {
    primaryKeyword: "gravy beef slow cook",
    primaryVolume: 140,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["slow cook beef and gravy", "chuck beef slow cook", "slow cook scotch fillet", "oyster blade slow cook", "slow cook beef in gravy"],
    weakPrimaryGated: false,
  },
  "The Wagyu Experience Luxury Sample Box (3.2kg)": {
    primaryKeyword: "meat box",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["wagyu box", "luxury wagyu beef", "wagyu beef box", "wagyu meat box", "wagyu steak box"],
    weakPrimaryGated: true,
  },
  "Sub-Zero Direct Wholesale Restock Crate (45kg)": {
    primaryKeyword: "meat box",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["farmer direct meat perth", "farmer direct meat", "farmers direct meat", "farm direct meat perth", "meat direct"],
    weakPrimaryGated: true,
  },
  "The Whole Beast Half-Cow Butchery Share (90kg)": {
    primaryKeyword: "half cow share",
    primaryVolume: 10,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["half a cow online", "how much is half a cow", "half cow meat package", "half cow brisbane", "butcher half a cow"],
    weakPrimaryGated: false,
  },
  "Southern Lamb Lover's Heritage Box (8kg)": {
    primaryKeyword: "meat box",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["whole lamb box", "lamb box prices", "lamb meat box", "full lamb box", "bbq in a box"],
    weakPrimaryGated: true,
  },
  "Smash Burger & Hotdog Weekend Bundle (6kg)": {
    primaryKeyword: "wagyu smash burger",
    primaryVolume: 30,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["smash wagyu burger", "wagyu smash burger recipe", "wagyu beef smash burger", "smash burger wagyu", "grass fed smash burger"],
    weakPrimaryGated: false,
  },
  "Organic Free-Range Poultry Farm Box (10kg)": {
    primaryKeyword: "organic free range chicken farm near me",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Transactional",
    supporting: ["organic free range chicken farm", "free range organic chicken farm", "organic free range chicken", "free range organic chicken", "farm fresh free range"],
    weakPrimaryGated: false,
  },
  "Artisan Sausage Maker's Variety Box (7kg)": {
    primaryKeyword: "meat variety box",
    primaryVolume: 10,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["beef box", "bbq in a box", "buy organic sausage online", "bulk sausage", "meat box"],
    weakPrimaryGated: false,
  },
  "The Texas Brisket & Ribs Duo Box (8kg)": {
    primaryKeyword: "wagyu brisket texas",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["texas wagyu brisket", "brisket vs short ribs", "short ribs vs brisket", "short ribs brisket", "beef box"],
    weakPrimaryGated: false,
  },
  "Native Australian Game Discovery Box (5kg)": {
    primaryKeyword: "australian meat box",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["wild game chiller box locations qld", "game meat subscription box", "game meat box", "beef box", "bbq in a box"],
    weakPrimaryGated: false,
  },
  "Sunday Roast Medley Family Box (7kg)": {
    primaryKeyword: "sunday roast beaconsfield",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["beef box", "bbq in a box", "roast eye fillet", "beef eye fillet roast", "eye fillet roast"],
    weakPrimaryGated: false,
  },
  "Lean Mince & Burger High-Volume Box (12kg)": {
    primaryKeyword: "extra lean beef mince",
    primaryVolume: 2400,
    primaryKd: 11.0,
    primaryIntent: "Commercial",
    supporting: ["lean beef mince", "lean mince meat", "lean mince", "extra lean mince", "lean mince beef"],
    weakPrimaryGated: false,
  },
  "Gourmet Breakfast Butcher Box (Bacon, Snags, Steaks)": {
    primaryKeyword: "box of steaks",
    primaryVolume: 30,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["steaks in a box", "box steaks", "butcher box", "box hill butcher", "butcher box australia"],
    weakPrimaryGated: false,
  },
  "The $423 Threshold Gateway Direct Box (22kg)": {
    primaryKeyword: "beef box",
    primaryVolume: 90,
    primaryKd: 1.0,
    primaryIntent: "Commercial",
    supporting: ["bbq in a box", "meat box", "what is meat box", "chicken box", "butcher box"],
    weakPrimaryGated: false,
  },
  "Free-Range Skinless Chicken Breast (2kg Bulk)": {
    primaryKeyword: "chicken breast free range",
    primaryVolume: 70,
    primaryKd: 4.0,
    primaryIntent: "Informational",
    supporting: ["free range chicken breast", "coles free range chicken breast", "coles chicken breast free range", "coles free range chicken breast carved roast", "free range chicken breast coles"],
    weakPrimaryGated: false,
  },
  "Free-Range Boneless Skinless Chicken Thigh (2kg)": {
    primaryKeyword: "free range chicken thigh",
    primaryVolume: 40,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["weight of boneless skinless chicken thigh", "how much does one boneless skinless chicken thigh weigh", "how much does a boneless skinless chicken thigh weigh", "boneless skinless chicken thigh weight", "average weight of a boneless skinless chicken thigh"],
    weakPrimaryGated: false,
  },
  "Whole Spatchcock Chicken with Lemon Pepper Herb": {
    primaryKeyword: "coles chicken lemon and herb",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Navigational",
    supporting: ["coles lemon and herb chicken breast", "coles lemon and herb chicken", "coles boneless chicken herb and garlic", "coles boneless chicken garlic and herb", "coles garlic and herb boneless chicken"],
    weakPrimaryGated: false,
  },
  "Chicken Breast & Angus Beef Rump Combo Pack (3kg)": {
    primaryKeyword: "angus beef rump steak",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["rump angus steak", "ground beef vs chicken breast protein", "does chicken breast have more protein than ground beef", "ground beef or chicken breast for protein", "does chicken breast or ground beef have more protein"],
    weakPrimaryGated: false,
  },
  "Free-Range Chicken Drumsticks (2kg Value Pack)": {
    primaryKeyword: "free range chicken drumsticks",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["free range drumsticks", "whole free range chicken", "buy free range chicken online", "free range chicken", "chicken breast free range"],
    weakPrimaryGated: false,
  },
  "Honey Soy Marinated Chicken Wingettes (2kg)": {
    primaryKeyword: "chicken mince",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["coles marinated chicken breast", "pre marinated chicken breast", "marinated chicken breast calories per 100g", "marinated meat near me", "marinated eye fillet recipes"],
    weakPrimaryGated: true,
  },
  "Whole Heritage Free-Range Roasting Bird (1.8kg)": {
    primaryKeyword: "roasting free range chicken",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["heritage free range turkey", "whole free range chicken", "buy free range chicken online", "free range chicken", "free range lamb"],
    weakPrimaryGated: false,
  },
  "Lean Chicken Breast Mince 98% Fat Free (1kg)": {
    primaryKeyword: "lean mince fat percentage",
    primaryVolume: 50,
    primaryKd: 20.0,
    primaryIntent: "Informational",
    supporting: ["fat free mince", "chicken breast free range", "free range chicken breast", "chicken breast mince", "extra lean chicken mince"],
    weakPrimaryGated: false,
  },
  "Crumbed Artisan Chicken Breast Schnitzels (6 pack)": {
    primaryKeyword: "coles crumbed chicken breast",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Navigational",
    supporting: ["chicken breast in bulk", "bulk chicken breast", "chicken breast per kg", "chicken breast 1kg", "1kg chicken breast"],
    weakPrimaryGated: false,
  },
  "Smoked Chicken Chorizo Sausages (1kg)": {
    primaryKeyword: "chicken mince",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["coles smoked chicken breast", "smoked chicken breast calories 100g", "buy smoked leg ham online", "smoked meats canberra", "smoked meat canberra"],
    weakPrimaryGated: true,
  },
  "Garlic Butter Kiev Stuffed Chicken Breasts (4 pack)": {
    primaryKeyword: "chicken mince",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["how much protein in 2 chicken breasts", "how many chicken breasts is 250g", "chicken breasts price", "cheap chicken breasts", "chicken breasts coles"],
    weakPrimaryGated: true,
  },
  "Chicken Tenderloins Hand-Trimmed (1.5kg)": {
    primaryKeyword: "chicken mince",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["free range chicken tenderloins", "pre trimmed chicken breast", "hand raised birds for sale canberra", "hand cut filet mignon", "chicken breast in bulk"],
    weakPrimaryGated: true,
  },
  "Portuguese Peri-Peri Marinated Half Chickens (2 pack)": {
    primaryKeyword: "half cattle",
    primaryVolume: 320,
    primaryKd: 1.0,
    primaryIntent: "Informational",
    supporting: ["half a cow online", "half cows", "how much is half a cow", "half cow meat package", "half cow brisbane"],
    weakPrimaryGated: false,
  },
  "Free-Range Chicken Bones & Necks for Broth (3kg)": {
    primaryKeyword: "free range chicken broth",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["whole free range chicken", "buy free range chicken online", "free range chicken", "chicken breast free range", "free range chicken breast"],
    weakPrimaryGated: false,
  },
  "French-Trimmed Southern Lamb Cutlets (8 pack)": {
    primaryKeyword: "lamb",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["best lamb cutlets in melbourne", "lamb cutlets melbourne", "eye fillet in french", "scotch fillet in french", "scotch fillet with french shallot sauce"],
    weakPrimaryGated: true,
  },
  "Slow-Roast Oyster Cut Lamb Shoulder (Bone-In 2kg)": {
    primaryKeyword: "lamb bone in shoulder roast",
    primaryVolume: 50,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["bone in lamb shoulder roast", "lamb shoulder roast bone in", "lamb shoulder bone in roast", "shoulder roast bone in", "can you slow cook oyster blade roast"],
    weakPrimaryGated: false,
  },
  "French-Trimmed Lamb Shank Duo Pack (900g)": {
    primaryKeyword: "lamb",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["eye fillet in french", "shoulder to shank butcher neutral bay", "scotch fillet in french", "scotch fillet with french shallot sauce", "short ribs in french"],
    weakPrimaryGated: true,
  },
  "Traditional Boneless Rolled Lamb Leg Roast with Rosemary": {
    primaryKeyword: "shoulder rolled roast boneless lamb",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["lamb shoulder rolled roast boneless", "lamb shoulder rolled roast boneless cooking time", "boneless rolled leg of lamb", "boneless rolled lamb roast", "rolled shoulder roast lamb"],
    weakPrimaryGated: false,
  },
  "Mediterranean Rosemary & Garlic Lamb Chops (1kg)": {
    primaryKeyword: "lamb",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["price for lamb chops", "lamb chops price per kg", "how to cook lamb loin chops in oven", "how to cook loin chops lamb", "how to cook lamb mid loin chops"],
    weakPrimaryGated: true,
  },
  "Pure Grass-Fed Lamb Mince (1kg)": {
    primaryKeyword: "grass fed mince",
    primaryVolume: 170,
    primaryKd: 7.0,
    primaryIntent: "Commercial",
    supporting: ["aldi grass fed mince", "grass fed mince aldi", "organic grass fed mince", "grass fed mince meat", "is grass fed mince better"],
    weakPrimaryGated: false,
  },
  "Whole Crown Roast of Lamb (16 Cutlets Tied)": {
    primaryKeyword: "rolled shoulder roast lamb",
    primaryVolume: 110,
    primaryKd: 23.0,
    primaryIntent: "Informational",
    supporting: ["lamb bone in shoulder roast", "bone in lamb shoulder roast", "lamb shoulder roast bone in", "roast leg of lamb price", "roast lamb rolled shoulder"],
    weakPrimaryGated: false,
  },
  "Moroccan Spiced Lamb Rump Steaks (3 x 200g)": {
    primaryKeyword: "rump cap steaks",
    primaryVolume: 50,
    primaryKd: 7.0,
    primaryIntent: "Informational",
    supporting: ["rump steaks", "rump steaks recipes", "difference between rump and sirloin steaks", "best way to cook rump steaks", "buy lamb rump steak online"],
    weakPrimaryGated: false,
  },
  "Diced Lamb Leg for Curry and Tagine (1kg)": {
    primaryKeyword: "how to cook diced leg of lamb",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["how to cook diced lamb leg", "leg of lamb cost", "leg of lamb prices", "price lamb leg", "cost of lamb leg"],
    weakPrimaryGated: false,
  },
  "Handcrafted Traditional Beef BBQ Sausages (2kg Mega)": {
    primaryKeyword: "smallgoods",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["best beef for bbq", "bbq beef burger", "beef eye fillet recipes bbq", "beef eye fillet bbq", "bbq whole fillet of beef"],
    weakPrimaryGated: true,
  },
  "Artisan Pork & Fennel Italian Style Sausages (1kg)": {
    primaryKeyword: "smallgoods",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["italian pork scotch fillet recipes", "how many italian sausages in a pound", "italian butchers near me", "italian butcher shop near me", "italian sausage organic"],
    weakPrimaryGated: true,
  },
  "Thick Beef & Caramelised Onion Sausage Snags (1.5kg)": {
    primaryKeyword: "kettle angus beef and caramelised onion halal",
    primaryVolume: 10,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["beef sausage", "mince beef sausage", "beef sausage organic", "grassfed beef sausage", "natural beef sausage"],
    weakPrimaryGated: false,
  },
  "Wood-Smoked Double-Cut Rindless Bacon Streaky (1kg)": {
    primaryKeyword: "smallgoods",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["beehive streaky bacon 1kg", "streaky bacon rasher weight", "streaky bacon price per kg", "streaky bacon australia", "streaky bacon 1kg"],
    weakPrimaryGated: true,
  },
  "Spanish Style Cured Chorizo Links (500g)": {
    primaryKeyword: "smallgoods",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["eye fillet in spanish", "wagyu in spanish", "spanish wagyu", "wagyu beef in spanish", "cured deli meat crossword clue"],
    weakPrimaryGated: true,
  },
  "Mild Cured Hungarian Salami Chub (400g)": {
    primaryKeyword: "smallgoods",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["cured deli meat crossword clue", "cured meats without nitrates", "hungarian butcher shop near me", "hungarian butcher near me", "cured meat subscription"],
    weakPrimaryGated: true,
  },
  "Hot Calabrese Soppressata Slices (200g)": {
    primaryKeyword: "wagyu beef slices",
    primaryVolume: 110,
    primaryKd: 2.0,
    primaryIntent: "Informational, Transactional",
    supporting: ["chicken breast slices", "a5 wagyu slices", "preservative free hot dogs", "nitrate free hot dogs", "short rib slices"],
    weakPrimaryGated: false,
  },
  "Old-Fashioned Double Smoked Leg Ham off the Bone (1kg)": {
    primaryKeyword: "buy smoked leg ham online",
    primaryVolume: 70,
    primaryKd: 4.0,
    primaryIntent: "Transactional",
    supporting: ["ham off the bone deli meat", "is deli ham off the bone processed", "what is ham off the bone deli meat", "beef leg bone", "bone and rolled leg of lamb"],
    weakPrimaryGated: false,
  },
  "Cheese Kransky with Jalapeno Hot Smoke (1kg)": {
    primaryKeyword: "smoke wagyu brisket",
    primaryVolume: 90,
    primaryKd: 12.0,
    primaryIntent: "Informational",
    supporting: ["smoke wagyu patties", "veal and cheese", "smoke wagyu cuts", "buy ham and cheese character online", "veal cheese"],
    weakPrimaryGated: false,
  },
  "Black Angus Cocktail Franks (1kg)": {
    primaryKeyword: "black angus rib eye steak",
    primaryVolume: 50,
    primaryKd: 0.0,
    primaryIntent: "Informational, Transactional",
    supporting: ["black angus porterhouse", "black angus eye fillet", "black angus rib fillet", "black angus beef ribeye", "black angus ribeye steak"],
    weakPrimaryGated: false,
  },
  "Cumberland Spiral English Pork Sausages (750g)": {
    primaryKeyword: "smallgoods",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["ojo de bife in english", "don english ham", "english style ham", "english butcher melbourne", "english butchers near me"],
    weakPrimaryGated: true,
  },
  "Smoked Polish Kielbasa with Garlic (800g)": {
    primaryKeyword: "buy smoked leg ham online",
    primaryVolume: 70,
    primaryKd: 4.0,
    primaryIntent: "Transactional",
    supporting: ["kielbasa sausage australia", "smoked meats canberra", "smoked meat canberra", "smoked eye fillet", "smoked wagyu beef"],
    weakPrimaryGated: false,
  },
  "Boerewors South African Spiced Beef Spiral (1kg)": {
    primaryKeyword: "south african butchers",
    primaryVolume: 30,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["south african fillet recipes", "south african butcher melbourne", "south african butcher brisbane", "south chicago packing wagyu beef tallow", "south chicago packing wagyu beef tallow spray"],
    weakPrimaryGated: false,
  },
  "Prosciutto Crudo Aged 18 Months (200g Sliced)": {
    primaryKeyword: "dry aged prosciutto",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["sliced wagyu", "dry aged beef online", "dry aged tomahawk", "dry aged rib eye", "buy sliced ham online"],
    weakPrimaryGated: false,
  },
  "Smoked Beef Pastrami for Reuben Sandwiches (500g)": {
    primaryKeyword: "smallgoods",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["smoked wagyu beef", "smoked wagyu beef brisket", "wagyu beef smoked", "smoked beef blade roast recipe", "smoked beef brisket for sale"],
    weakPrimaryGated: true,
  },
  "Bavarian Style Bratwurst Pork Sausages (1kg)": {
    primaryKeyword: "smallgoods",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["nitrate free bratwurst", "organic bratwurst", "how many sausages to a kilo", "how many sausages in a kilo", "preservative free sausages"],
    weakPrimaryGated: true,
  },
  "Duck & Plum Gourmet Dinner Sausages (600g)": {
    primaryKeyword: "dry aged duck",
    primaryVolume: 90,
    primaryKd: 8.0,
    primaryIntent: "Informational",
    supporting: ["recipes for dinner with mince", "mince dinner meals", "dinner mince", "dinner idea with mince", "peking duck rockhampton"],
    weakPrimaryGated: false,
  },
  "Wagyu & Truffle Handcrafted Sausages (600g)": {
    primaryKeyword: "smallgoods",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["filet mignon with truffle butter", "how many sausages to a kilo", "how many sausages in a kilo", "preservative free sausages", "bulk sausages"],
    weakPrimaryGated: true,
  },
  "Lamb Merguez Spicy Moroccan Links (700g)": {
    primaryKeyword: "smallgoods",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["spicy deli meat", "spicy fillet steak recipes", "spicy steak recipe", "spicy steak recipes", "links butcher"],
    weakPrimaryGated: true,
  },
  "Pancetta Flat Cured Italian Bacon (300g Sliced)": {
    primaryKeyword: "smallgoods",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["dry cured bacon australia", "does dry cured bacon contain nitrates", "sliced wagyu", "buy sliced ham online", "italian butchers near me"],
    weakPrimaryGated: true,
  },
  "Traditional Blood Pudding (Black Pudding) Chubs (400g)": {
    primaryKeyword: "smallgoods",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["black angus rib eye steak", "black angus porterhouse", "black angus eye fillet", "black angus rib fillet", "full blood wagyu"],
    weakPrimaryGated: true,
  },
  "Smoked Strasburg Deli Slices (500g)": {
    primaryKeyword: "deli smoked ham",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["mahogany smoked meats deli", "smoked deli meats", "smoked ham deli", "smoked meat deli near me", "smoked deli meat"],
    weakPrimaryGated: false,
  },
  "Skinless Chipolata Breakfast Sausages (1kg)": {
    primaryKeyword: "smallgoods",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["organic breakfast sausages", "applegate breakfast sausages", "protein in skinless chicken breast", "breakfast liver", "skinless chicken breast protein"],
    weakPrimaryGated: true,
  },
  "Free-Range Heritage Pork Belly with Scored Rind (2kg)": {
    primaryKeyword: "free range pork sausages",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["free range pork melbourne", "organic free range pork near me", "free range pork farm", "wagga free range pork", "free range pork wholesale"],
    weakPrimaryGated: false,
  },
  "St. Louis Competition Cut Pork Ribs (2 Racks, 2.2kg)": {
    primaryKeyword: "buy pork online",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["pork ribs near me butcher", "pork ribs butcher near me", "are short ribs pork", "is short ribs pork", "pork short ribs cut"],
    weakPrimaryGated: true,
  },
  "American Boston Pork Butt for Pulled Pork (3.5kg)": {
    primaryKeyword: "buy pork online",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["pulled pork cuts of meat", "can you use pork scotch roast for pulled pork", "is pork scotch fillet good for pulled pork", "pork scotch fillet american equivalent", "pork scotch fillet pulled pork"],
    weakPrimaryGated: true,
  },
  "Thick-Cut Berkshire Pork Loin Cutlets Bone-In (4 x 300g)": {
    primaryKeyword: "pork bone in loin",
    primaryVolume: 50,
    primaryKd: 14.0,
    primaryIntent: "Informational",
    supporting: ["pork shoulder bone", "is bone marrow beef or pork", "bone marrow pork or beef", "bone in pork cuts", "pork bone cuts"],
    weakPrimaryGated: false,
  },
  "Rolled Boneless Pork Loin Roast with Crispy Skin (2kg)": {
    primaryKeyword: "boneless pork scotch roast",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["rolled scotch pork roast", "boneless pork loin price", "boneless shoulder roast", "rolled scotch fillet roast", "boneless roast"],
    weakPrimaryGated: false,
  },
  "Pork Scotch Fillet Steaks (Neck Collar) (4 x 250g)": {
    primaryKeyword: "pork scotch fillet steaks",
    primaryVolume: 40,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["best way to cook pork scotch fillet steaks", "how to cook pork scotch fillet steaks", "is pork neck the same as pork scotch fillet", "is pork scotch fillet the same as pork neck", "pork neck scotch fillet"],
    weakPrimaryGated: false,
  },
  "Baby Back Loin Pork Ribs (2 Racks, 1.6kg)": {
    primaryKeyword: "back ribs vs short ribs",
    primaryVolume: 30,
    primaryKd: 19.0,
    primaryIntent: "Commercial",
    supporting: ["short ribs vs back ribs", "are back ribs and short ribs the same", "are back ribs the same as short ribs", "difference between back ribs and short ribs", "difference between short ribs and back ribs"],
    weakPrimaryGated: false,
  },
  "Free-Range Pork Mince (1kg)": {
    primaryKeyword: "free range mince",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["free range pork sausages", "free range pork melbourne", "organic free range pork near me", "free range pork farm", "wagga free range pork"],
    weakPrimaryGated: false,
  },
  "Marinated Chinese Char Siu Pork Fillet Strips (800g)": {
    primaryKeyword: "marinated pork scotch fillet",
    primaryVolume: 50,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["chinese roast pork fillet", "pork scotch fillet chinese recipes", "pork scotch fillet recipe chinese", "marinated eye fillet recipes", "marinated eye fillet"],
    weakPrimaryGated: false,
  },
  "Pork Fillet / Tenderloin Duo Pack (750g)": {
    primaryKeyword: "is tenderloin the same as eye fillet",
    primaryVolume: 50,
    primaryKd: 5.0,
    primaryIntent: "Informational",
    supporting: ["tenderloin eye fillet", "eye fillet tenderloin", "tenderloin vs eye fillet", "is tenderloin eye fillet", "is eye fillet the same as tenderloin"],
    weakPrimaryGated: false,
  },
  "Pickled Pickled Pork Leg for Boiling (1.8kg)": {
    primaryKeyword: "buy pork online",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["pork leg price", "pork leg price per kg", "whole pork leg price", "dry aged pork leg", "leg of pork price per kilo"],
    weakPrimaryGated: true,
  },
  "Smoked Pork Knuckle (Eisbein) for Roasting (1.2kg)": {
    primaryKeyword: "buy pork online",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["smoked pork scotch fillet", "smoked pork scotch roast", "roasting eye fillet", "buy smoked leg ham online", "smoked meats canberra"],
    weakPrimaryGated: true,
  },
  "Pork Cutlets Marinated in Apple, Honey & Sage (3 pack)": {
    primaryKeyword: "buy pork online",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["marinated pork scotch fillet", "honey soy pork scotch fillet", "marinated meat near me", "marinated eye fillet recipes", "marinated eye fillet"],
    weakPrimaryGated: true,
  },
  "Crispy Pork Belly Strips Pre-Sliced for Stir-Fry (600g)": {
    primaryKeyword: "pork scotch fillet stir fry",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["pork scotch fillet stir fry recipes", "eye fillet stir fry", "is rump steak good for stir fry", "scotch fillet stir fry", "stir fry rump steak"],
    weakPrimaryGated: false,
  },
  "Wild Australian Kangaroo Fillets Skinless (1kg)": {
    primaryKeyword: "australian butchers",
    primaryVolume: 2400,
    primaryKd: 19.0,
    primaryIntent: "Navigational",
    supporting: ["australian meat emporium", "eye fillets", "australian butchers store", "scotch fillets", "australian butcher store berwick"],
    weakPrimaryGated: false,
  },
  "Pure Kangaroo Mince Ultra-Lean (1kg)": {
    primaryKeyword: "lean mince meat",
    primaryVolume: 1600,
    primaryKd: 11.0,
    primaryIntent: "Informational",
    supporting: ["lean mince", "extra lean mince", "mince lean", "lean mince protein", "lean mince fat percentage"],
    weakPrimaryGated: false,
  },
  "Marinated Native Pepperberry Kangaroo Steaks (600g)": {
    primaryKeyword: "wholesale ribeye steaks",
    primaryVolume: 90,
    primaryKd: 2.0,
    primaryIntent: "Informational",
    supporting: ["eye fillet steaks", "scotch fillet steaks", "rump cap steaks", "deals on steaks near me", "tomahawk steaks"],
    weakPrimaryGated: false,
  },
  "Wild Australian Venison Striploin Steaks (400g)": {
    primaryKeyword: "wholesale ribeye steaks",
    primaryVolume: 90,
    primaryKd: 2.0,
    primaryIntent: "Informational",
    supporting: ["eye fillet steaks", "australian butchers", "australian meat emporium", "australian butchers store", "scotch fillet steaks"],
    weakPrimaryGated: false,
  },
  "Slow-Braised Venison Osso Buco Shanks (800g)": {
    primaryKeyword: "slow braised chuck",
    primaryVolume: 10,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["oyster blade steak slow cooker recipes", "cuts of meat for slow cooker", "slow cooker scotch fillet", "slow cook scotch fillet", "eye fillet slow cooker recipes"],
    weakPrimaryGated: false,
  },
  "Wild Boar Sausages with Native Thyme (600g)": {
    primaryKeyword: "kangaroo meat",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["native chicken", "boar's head deli meat", "boar's head deli ham", "deli meat boar's head", "wild turkeys for sale near me"],
    weakPrimaryGated: true,
  },
  "Kangaroo Rump Roasts Whole (1.2kg)": {
    primaryKeyword: "kangaroo meat",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["kangaroo rump", "what is kangaroo rump", "buy rump steak online", "250g rump steak", "grass fed rump"],
    weakPrimaryGated: true,
  },
  "Wild Wallaby Fillets Tenderised (500g)": {
    primaryKeyword: "eye fillets",
    primaryVolume: 90,
    primaryKd: 6.0,
    primaryIntent: "Informational, Transactional",
    supporting: ["pork scotch fillets", "scotch fillets", "fillets of beef", "beef fillets", "how many eye fillets in a cow"],
    weakPrimaryGated: false,
  },
  "Crocodile Tail Fillet Medallions (400g)": {
    primaryKeyword: "eye fillet medallions",
    primaryVolume: 30,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["beef eye fillet tail", "eye fillet tail", "beef eye fillet tail recipe", "beef fillet tail", "how to cook eye fillet tail"],
    weakPrimaryGated: false,
  },
  "Smoked Kangaroo Prosciutto Bresaola (150g)": {
    primaryKeyword: "buy smoked leg ham online",
    primaryVolume: 70,
    primaryKd: 4.0,
    primaryIntent: "Transactional",
    supporting: ["smoked meats canberra", "smoked meat canberra", "smoked eye fillet", "eye fillet wrapped in prosciutto recipe", "eye fillet wrapped in prosciutto"],
    weakPrimaryGated: false,
  },
  "Wild Game Mixed Stewing Meat (Diced 1kg)": {
    primaryKeyword: "kangaroo meat",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["diced meat", "diced goat meat near me", "wild meat butcher near me", "what cut of meat is diced beef", "diced meat meaning"],
    weakPrimaryGated: true,
  },
  "Kangaroo Tail Sections for Slow-Cooked Stew (1.5kg)": {
    primaryKeyword: "eye fillet slow cooked",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["slow cooked eye fillet", "slow cooked eye fillet steak", "slow cooked eye fillet recipe", "can scotch fillet be slow cooked", "slow cooked scotch fillet in oven"],
    weakPrimaryGated: false,
  },
  "Lean Wild Game Burger Patties (6 x 150g)": {
    primaryKeyword: "bulk burger patties",
    primaryVolume: 90,
    primaryKd: 6.0,
    primaryIntent: "Commercial",
    supporting: ["wagyu beef burger patties", "how many burger patties per cow", "ground beef burger patties", "besten burger patties", "best homemade burger patties"],
    weakPrimaryGated: false,
  },
  "Coral Coast Barramundi Mid-Cut Fillets (2 x 180g)": {
    primaryKeyword: "eye fillets",
    primaryVolume: 90,
    primaryKd: 6.0,
    primaryIntent: "Informational, Transactional",
    supporting: ["scotch fillets", "meat delivery gold coast", "butchers central coast", "butcher central coast", "gold coast meat delivery"],
    weakPrimaryGated: false,
  },
  "Aquna Murray Cod Fresh Centre Fillets (2 x 180g)": {
    primaryKeyword: "eye fillets",
    primaryVolume: 90,
    primaryKd: 6.0,
    primaryIntent: "Informational, Transactional",
    supporting: ["scotch fillets", "port macquarie meat centre", "butcher canberra centre", "centre cut fillet", "centre cut eye fillet"],
    weakPrimaryGated: false,
  },
  "Yarra Valley Australian Salmon Caviar Tin (50g)": {
    primaryKeyword: "australian butchers",
    primaryVolume: 2400,
    primaryKd: 19.0,
    primaryIntent: "Navigational",
    supporting: ["australian meat emporium", "australian butchers store", "australian butcher store berwick", "australian butcher store", "australian wholesale meats"],
    weakPrimaryGated: false,
  },
  "King Prawns Wild Australian Cleaned & Peeled (500g)": {
    primaryKeyword: "australian butchers",
    primaryVolume: 2400,
    primaryKd: 19.0,
    primaryIntent: "Navigational",
    supporting: ["australian meat emporium", "australian butchers store", "australian butcher store berwick", "australian butcher store", "australian wholesale meats"],
    weakPrimaryGated: false,
  },
  "Tasmanian Atlantic Salmon Portions Skin-On (4 x 180g)": {
    primaryKeyword: "tasmanian quality meats",
    primaryVolume: 260,
    primaryKd: 28.0,
    primaryIntent: "Navigational",
    supporting: ["tasmanian prime meat launceston", "tasmanian butcher", "tasmanian prime meats", "tasmanian prime meat reviews", "skin pack meat"],
    weakPrimaryGated: false,
  },
  "Harvey Bay Sea Scallops Roe-Off (300g)": {
    primaryKeyword: "neutral bay butcher",
    primaryVolume: 70,
    primaryKd: 12.0,
    primaryIntent: "Commercial",
    supporting: ["butcher rose bay", "rose bay butcher", "what does off beef mince smell like", "east coast meats warners bay", "what does off mince look like"],
    weakPrimaryGated: false,
  },
  "Milk-Fed Veal Osso Buco Shank Cross-Cuts (800g)": {
    primaryKeyword: "milk fed veal",
    primaryVolume: 40,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["veal milk fed", "milk fed veal cutlets", "what is milk fed veal", "grass fed veal", "veal in milk"],
    weakPrimaryGated: false,
  },
  "Milk-Fed Veal Cutlets Bone-In (4 x 220g)": {
    primaryKeyword: "milk fed veal cutlets",
    primaryVolume: 30,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["milk fed veal", "veal milk fed", "what is milk fed veal", "grass fed bone marrow bones", "bone marrow grass fed"],
    weakPrimaryGated: false,
  },
  "Tender Veal Scallopini Thin Cutlets (500g)": {
    primaryKeyword: "meat veal",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["milk fed veal cutlets", "tender veal", "grilled veal cutlets", "is scotch fillet tender", "tender west meats"],
    weakPrimaryGated: true,
  },
  "Veal Mince Premium Delicate Blend (1kg)": {
    primaryKeyword: "can you blend mince meat",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["veal mince", "what is veal mince", "roo mince", "bulk mince", "lean mince meat"],
    weakPrimaryGated: false,
  },
  "Rolled Boneless Veal Shoulder Roast (1.5kg)": {
    primaryKeyword: "boneless shoulder roast",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["shoulder roast boneless", "shoulder roast bone in", "boneless shoulder", "rolled scotch fillet roast", "roast boneless"],
    weakPrimaryGated: false,
  },
  "Butcher Master Hand-Forged Cleaver 7-Inch": {
    primaryKeyword: "butcher equipment",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["1 inch scotch fillet cooking time", "how long to cook 1 inch scotch fillet", "2 inch fillet steak cooking times", "1 inch wagyu steak cook time", "how long to cook 1 inch wagyu steak"],
    weakPrimaryGated: true,
  },
  "Dual-Probe Bluetooth Instant Meat Thermometer": {
    primaryKeyword: "butcher equipment",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["frozen meat instant pot", "rump steak instant pot", "beef blade roast instant pot", "blade roast instant pot", "blade roast recipe instant pot"],
    weakPrimaryGated: true,
  },
  "Australian Ironbark Smoker Chunks (10kg Bag)": {
    primaryKeyword: "australian butchers",
    primaryVolume: 2400,
    primaryKd: 19.0,
    primaryIntent: "Navigational",
    supporting: ["australian meat emporium", "australian wagyu price per kg", "australian butchers store", "australian tenderloin beef", "australian wagyu price"],
    weakPrimaryGated: false,
  },
  "Pitmaster Texas Gold Brisket Dry Rub Tin (300g)": {
    primaryKeyword: "wagyu brisket texas",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["texas wagyu brisket", "dry aged beef gold coast", "dry aged beef brisket", "dry aged brisket", "dry aged smoked brisket"],
    weakPrimaryGated: false,
  },
  "Heavy Duty Meat Vacuum Sealer Machine Pro": {
    primaryKeyword: "butcher equipment",
    primaryVolume: 0,
    primaryKd: 0,
    primaryIntent: "Informational",
    supporting: ["vacuum sealed frozen meat", "frozen vacuum sealed meat", "dry aged meat machine", "vacuum sealed deli meat", "vacuum packed mince"],
    weakPrimaryGated: true,
  },
  "Insulated Heavy Duty Cold-Chain Thermal Delivery Box (60L)": {
    primaryKeyword: "cold meat delivery",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Transactional",
    supporting: ["cold cuts delivery", "frozen goods delivery", "wagyu delivery", "beef mince delivery", "rump steak delivery"],
    weakPrimaryGated: false,
  },
};

export const CATEGORY_KEYWORDS: Record<string, ProductKeywordEntry> = {
  "beef": {
    primaryKeyword: "beef mince",
    primaryVolume: 4400,
    primaryKd: 17,
    primaryIntent: "Informational, Commercial",
    supporting: ["extra lean beef mince", "lean beef mince", "bulk beef mince", "buy organic beef mince online", "beef mince melbourne"],
    weakPrimaryGated: false,
  },
  "chicken": {
    primaryKeyword: "chicken mince",
    primaryVolume: 3600,
    primaryKd: 23,
    primaryIntent: "Informational",
    supporting: ["halal chicken mince", "chicken breast mince", "mince chicken", "extra lean chicken mince", "coles chicken breast mince"],
    weakPrimaryGated: false,
  },
  "lamb": {
    primaryKeyword: "whole lamb cut and packed",
    primaryVolume: 50,
    primaryKd: 1.0,
    primaryIntent: "Informational",
    supporting: ["full lamb", "whole lamb meat prices", "lamb for sale melbourne", "buy lamb rump steak online", "lamb meat"],
    weakPrimaryGated: false,
  },
  "smallgoods": {
    primaryKeyword: "ballarat wholesale smallgoods",
    primaryVolume: 30,
    primaryKd: 19.0,
    primaryIntent: "Commercial",
    supporting: ["butcher and smallgoods maker", "ballarat smallgoods", "papandrea smallgoods", "wholesale smallgoods melbourne", "codemo smallgoods griffith"],
    weakPrimaryGated: false,
  },
  "meatboxes": {
    primaryKeyword: "meat box",
    primaryVolume: 2400,
    primaryKd: 23,
    primaryIntent: "Commercial",
    supporting: ["what is meat box", "box for meat", "meat box wa", "meat box perth", "meat subscription box"],
    weakPrimaryGated: false,
  },
  "pork": {
    primaryKeyword: "buy pork online",
    primaryVolume: 210,
    primaryKd: 6,
    primaryIntent: "Transactional",
    supporting: ["buy pork mince online", "buy pork bones online", "buy mince pork sausage online", "buy frozen pork online", "buy mince pork online"],
    weakPrimaryGated: false,
  },
  "seafood": {
    primaryKeyword: "best price butcher & seafood",
    primaryVolume: 480,
    primaryKd: 22.0,
    primaryIntent: "Commercial",
    supporting: ["organic meat and seafood delivery", "seafood hampers delivered", "carnivore seafood", "is crocodile considered seafood", "seafood market kingston"],
    weakPrimaryGated: false,
  },
  "wagyu": {
    primaryKeyword: "wagyu beef",
    primaryVolume: 8100,
    primaryKd: 32,
    primaryIntent: "Informational",
    supporting: ["wagyu beef slices", "a5 beef wagyu", "wagyu beef flank steak", "wagyu beef rump steak", "wagyu beef sirloin"],
    weakPrimaryGated: false,
  },
  "kangaroo-game": {
    primaryKeyword: "minced kangaroo meat",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Informational",
    supporting: ["kangaroo meat mince", "kangaroo mince meat", "bbq meat packs", "meat pack", "barbecue meat packs"],
    weakPrimaryGated: false,
  },
  "veal": {
    primaryKeyword: "meat veal",
    primaryVolume: 6600,
    primaryKd: 11,
    primaryIntent: "Informational",
    supporting: ["lean veal meat", "veal meat online", "veal ground meat", "bbq meat packs", "meat pack"],
    weakPrimaryGated: false,
  },
  "equipment": {
    primaryKeyword: "butcher equipment near me",
    primaryVolume: 20,
    primaryKd: 19.0,
    primaryIntent: "Transactional",
    supporting: ["butcher equipment for sale near me", "m&s butcher equipment", "butcher equipment shop", "butchery equipment near me", "butchers equipment near me"],
    weakPrimaryGated: false,
  },
};